language: generic

node_js:
  - "8"

sudo: required

services:
  - docker

script:
  - docker run \
    --name emscripten \
    -v $(pwd):/src \
    -it trzeci/emscripten-ubuntu:sdk-incoming-64bit \
    sh -c "apt-get update;apt-get install file -y;make 2>&1 | tee log.txt"
  
