ui: tape
server: "http-server -p $ZUUL_PORT"
browsers:
  - name: ipad
    version: latest
  - name: firefox
    version: latest
  - name: iphone
    version: latest
  - name: safari
    version: latest
  - name: chrome
    version: latest
  - name: internet explorer
    version: latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: latest
  - name: android
    version: latest
browserify:
  - transform: babelify
    presets:
      - es2015
  - debug: true
